# Generated by Django 4.2.2 on 2023-06-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_todo_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['due_date']},
        ),
    ]
