# Generated by Django 4.2.2 on 2023-06-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_tags_alter_todo_assigned_to_alter_todo_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
